//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlPatio
{
    using System;
    using System.Collections.ObjectModel;
    using System.Collections.Generic;
    
    public partial class Eir
    {
        public Eir()
        {
            this.PuntosB = new ObservableCollection<PuntosB>();
            this.PuntosF = new ObservableCollection<PuntosF>();
            this.PuntosV = new ObservableCollection<PuntosV>();
        }
    
        public int EirFolio { get; set; }
        public int EirIdEntradaSalida { get; set; }
        public Nullable<byte> EirOperacion { get; set; }
        public string EirContenedor { get; set; }
        public Nullable<System.DateTime> EirFechaElabora { get; set; }
        public string EirObservaciones { get; set; }
    
        public virtual ICollection<PuntosB> PuntosB { get; set; }
        public virtual ICollection<PuntosF> PuntosF { get; set; }
        public virtual ICollection<PuntosV> PuntosV { get; set; }
        public virtual EntradaSalida EntradaSalida { get; set; }
    }
}
