//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlPatio
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ControlPatioEntities : DbContext
    {
        public ControlPatioEntities()
            : base("name=ControlPatioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AgenteAduanal> AgenteAduanal { get; set; }
        public virtual DbSet<Buque> Buque { get; set; }
        public virtual DbSet<Calidad> Calidad { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<CodigoDaño> CodigoDaño { get; set; }
        public virtual DbSet<Eir> Eir { get; set; }
        public virtual DbSet<Naviera> Naviera { get; set; }
        public virtual DbSet<PuntosB> PuntosB { get; set; }
        public virtual DbSet<PuntosF> PuntosF { get; set; }
        public virtual DbSet<PuntosV> PuntosV { get; set; }
        public virtual DbSet<TipoContenedor> TipoContenedor { get; set; }
        public virtual DbSet<Transporte> Transporte { get; set; }
        public virtual DbSet<EntradaSalida> EntradaSalida { get; set; }
    }
}
