//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlPatio
{
    using System;
    using System.Collections.ObjectModel;
    using System.Collections.Generic;
    
    public partial class PuntosB
    {
        public int PuntosBId { get; set; }
        public int PuntosBEirId { get; set; }
        public string PuntosBTipoDaño { get; set; }
        public int PuntosBDañoId { get; set; }
        public Nullable<int> PuntosBOrden { get; set; }
        public Nullable<int> PuntosB_X { get; set; }
        public Nullable<int> PuntosB_Y { get; set; }
    
        public virtual CodigoDaño CodigoDaño { get; set; }
        public virtual Eir Eir { get; set; }
    }
}
