//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlPatio
{
    using System;
    using System.Collections.ObjectModel;
    using System.Collections.Generic;
    
    public partial class PuntosF
    {
        public int PuntosFId { get; set; }
        public int PuntosFEirId { get; set; }
        public string PuntosFTipoDaño { get; set; }
        public int PuntosFDañoId { get; set; }
        public Nullable<int> PuntosFOrden { get; set; }
        public Nullable<int> PuntosF_X { get; set; }
        public Nullable<int> PuntosF_Y { get; set; }
    
        public virtual CodigoDaño CodigoDaño { get; set; }
        public virtual Eir Eir { get; set; }
    }
}
