//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlPatio
{
    using System;
    using System.Collections.ObjectModel;
    using System.Collections.Generic;
    
    public partial class PuntosV
    {
        public int PuntosVId { get; set; }
        public int PuntosVEirId { get; set; }
        public string PuntosVTipoDaño { get; set; }
        public int PuntosVDañoId { get; set; }
        public Nullable<int> PuntosVOrden { get; set; }
        public Nullable<int> PuntosV_X { get; set; }
        public Nullable<int> PuntosV_Y { get; set; }
    
        public virtual CodigoDaño CodigoDaño { get; set; }
        public virtual Eir Eir { get; set; }
    }
}
