//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlPatio
{
    using System;
    using System.Collections.ObjectModel;
    using System.Collections.Generic;
    
    public partial class TipoContenedor
    {
        public TipoContenedor()
        {
            this.EntradaSalida = new ObservableCollection<EntradaSalida>();
        }
    
        public int TamId { get; set; }
        public string TamDimension { get; set; }
        public string TamTipo { get; set; }
        public string TamDescripcion { get; set; }
    
        public virtual ICollection<EntradaSalida> EntradaSalida { get; set; }
    }
}
